name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Verificar versão do Python
        run: python --version

      - name: Executar main.py
        run: python main.py