name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verificar versão do Python
      run: python --version

    - name: Testar execução do main.py
      run: python main.py

    - name: Enviar alerta para o Discord
      if: always()
      run: |
        STATUS="${{ job.status }}"
        curl -H "Content-Type: application/json" \
        -X POST \
        -d "{\"content\": \"CI/CD executado: $STATUS\"}" \
        ${{ secrets.DISCORD_WEBHOOK }}
